services:
  job-application-tracker.web:
    container_name: job-application-tracker.web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm start